Minor bugfix to secrets --file args read
Example steps to reproduce the error before fix:
```
$ echo -n 'bla' | kapitan secrets --write gpg:secrets/common/test_targets/gcp_project_id -f - -t test_terraform_dummy
Traceback (most recent call last):
  File "/Users/rjmco/.pyenv/versions/3.7.0/bin/kapitan", line 11, in <module>
    load_entry_point('kapitan==0.18.2', 'console_scripts', 'kapitan')()
  File "/Users/rjmco/.pyenv/versions/3.7.0/lib/python3.7/site-packages/kapitan/cli.py", line 279, in main
    secret_write(args, ref_controller)
  File "/Users/rjmco/.pyenv/versions/3.7.0/lib/python3.7/site-packages/kapitan/cli.py", line 291, in secret_write
    file_name = args.file_name
AttributeError: 'Namespace' object has no attribute 'file_name'
```

(cherry picked from commit 76699ebe7a3deb81ba64b099395a285e91893b49)