Better compile errors (#1312)
When `kapitan compile` fails, it shows a massive strack trace which is
not helpful for users.

Example, in the `examples` folder, if I make this forced error in the
kadet template

```diff
$ git diff -U2 .
diff --git i/examples/kubernetes/components/nginx-kadet/__init__.py w/examples/kubernetes/components/nginx-kadet/__init__.py
index a3b37f5..97cadb1 100644
--- i/examples/kubernetes/components/nginx-kadet/__init__.py
+++ w/examples/kubernetes/components/nginx-kadet/__init__.py
@@ -16,4 +16,5 @@ svc_port.root.port = 80
 svc_port.root.targetPort = 80
 
+invalid_code
 
 def main():
```

<details>

<summary>Then we get this massive stack trace</summary>

```
kapitan compile 
Rendered inventory (0.07s): discovered 10 targets.
Compiling 10/10 targets using 8 concurrent processes: (8 CPU detected)
Compiled removal (0.00s)
Compiled busybox (0.12s)
Compiled jsonnet-env (0.07s)
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/kapitan/targets.py", line 264, in compile_target
    input_compiler.compile_obj(compile_config)
  File "/opt/venv/lib/python3.11/site-packages/kapitan/inputs/base.py", line 74, in compile_obj
    self.compile_input_path(comp_obj, expanded_path)
  File "/opt/venv/lib/python3.11/site-packages/kapitan/inputs/base.py", line 163, in compile_input_path
    self.compile_file(
  File "/opt/venv/lib/python3.11/site-packages/kapitan/inputs/kadet.py", line 113, in compile_file
    spec.loader.exec_module(kadet_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/src/components/nginx-kadet/__init__.py", line 18, in <module>
    invalid_code
NameError: name 'invalid_code' is not defined
Compiled labels (0.12s)


Error compiling minikube-nginx-kadet: name 'invalid_code' is not defined
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/kapitan/targets.py", line 264, in compile_target
    input_compiler.compile_obj(compile_config)
  File "/opt/venv/lib/python3.11/site-packages/kapitan/inputs/base.py", line 74, in compile_obj
    self.compile_input_path(comp_obj, expanded_path)
  File "/opt/venv/lib/python3.11/site-packages/kapitan/inputs/base.py", line 163, in compile_input_path
    self.compile_file(
  File "/opt/venv/lib/python3.11/site-packages/kapitan/inputs/kadet.py", line 113, in compile_file
    spec.loader.exec_module(kadet_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/src/components/nginx-kadet/__init__.py", line 18, in <module>
    invalid_code
NameError: name 'invalid_code' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/kapitan/targets.py", line 279, in compile_target
    raise CompileError(f"Error compiling {target_name}: {e}") from e
kapitan.errors.CompileError: Error compiling minikube-nginx-kadet: name 'invalid_code' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/kapitan/targets.py", line 129, in compile_targets
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/opt/venv/lib/python3.11/site-packages/kapitan/targets.py", line 129, in <listcomp>
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
kapitan.errors.CompileError: Error compiling minikube-nginx-kadet: name 'invalid_code' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/bin/kapitan", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/kapitan/cli.py", line 639, in main
    args.func(args)
  File "/opt/venv/lib/python3.11/site-packages/kapitan/cli.py", line 76, in trigger_compile
    compile_targets(
  File "/opt/venv/lib/python3.11/site-packages/kapitan/targets.py", line 170, in compile_targets
    raise CompileError(f"Error compiling targets: {e}")
kapitan.errors.CompileError: Error compiling targets: Error compiling minikube-nginx-kadet: name 'invalid_code' is not defined
```

</details>


## AFTER

much shorter and helpful error message

```
kapitan compile 
Rendered inventory (0.07s): discovered 10 targets.
Compiling 10/10 targets using 8 concurrent processes: (8 CPU detected)
Compiled removal (0.00s)
Compiled jsonnet-env (0.08s)
Compiled busybox (0.13s)
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/kapitan/targets.py", line 265, in compile_target
    input_compiler.compile_obj(compile_config)
  File "/opt/venv/lib/python3.11/site-packages/kapitan/inputs/base.py", line 74, in compile_obj
    self.compile_input_path(comp_obj, expanded_path)
  File "/opt/venv/lib/python3.11/site-packages/kapitan/inputs/base.py", line 163, in compile_input_path
    self.compile_file(
  File "/opt/venv/lib/python3.11/site-packages/kapitan/inputs/kadet.py", line 113, in compile_file
    spec.loader.exec_module(kadet_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/src/components/nginx-kadet/__init__.py", line 18, in <module>
    invalid_code
NameError: name 'invalid_code' is not defined


Error compiling minikube-nginx-kadet: name 'invalid_code' is not defined
```

It's also better for other input types. Example for jsonnet

```
kapitan compile 
Rendered inventory (0.08s): discovered 10 targets.
Compiling 10/10 targets using 8 concurrent processes: (8 CPU detected)
Compiled removal (0.00s)
Compiled busybox (0.13s)
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/kapitan/targets.py", line 265, in compile_target
    input_compiler.compile_obj(compile_config)
  File "/opt/venv/lib/python3.11/site-packages/kapitan/inputs/base.py", line 74, in compile_obj
    self.compile_input_path(comp_obj, expanded_path)
  File "/opt/venv/lib/python3.11/site-packages/kapitan/inputs/base.py", line 163, in compile_input_path
    self.compile_file(
  File "/opt/venv/lib/python3.11/site-packages/kapitan/inputs/jsonnet.py", line 82, in compile_file
    json_output = jsonnet.evaluate_file(
                  ^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: STATIC ERROR: /src/components/nginx-jsonnet/main.jsonnet:7:5-21: expected a comma before next field.

Compiled jsonnet-env (0.13s)


Error compiling minikube-nginx-jsonnet: STATIC ERROR: /src/components/nginx-jsonnet/main.jsonnet:7:5-21: expected a comma before next field.
```